// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafaFoods.Infrastructure.Persistence;

#nullable disable

namespace SafaFoods.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SafaFoodsDbContext))]
    [Migration("20260407040003_AddPaymentTrackingAndAdminAccess")]
    partial class AddPaymentTrackingAndAdminAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafaFoods.Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DeliveryZoneId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsServiceable")
                        .HasColumnType("boolean");

                    b.Property<string>("Landmark")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryZoneId");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("MarketingOptIn")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ShopifyCustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("ShopifyCustomerId")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.DeliveryZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedMaxMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("EstimatedMinMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fee")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MinKm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("delivery_zones", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f9f0f95-7408-44ad-a6f2-6f30f3e9a101"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 460, DateTimeKind.Unspecified).AddTicks(4618), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedMaxMinutes = 45,
                            EstimatedMinMinutes = 30,
                            Fee = 10m,
                            IsActive = true,
                            MaxKm = 3m,
                            MinKm = 0m,
                            Name = "Zone A",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 460, DateTimeKind.Unspecified).AddTicks(4624), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("4f9f0f95-7408-44ad-a6f2-6f30f3e9a102"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 461, DateTimeKind.Unspecified).AddTicks(4239), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedMaxMinutes = 70,
                            EstimatedMinMinutes = 45,
                            Fee = 20m,
                            IsActive = true,
                            MaxKm = 8m,
                            MinKm = 3m,
                            Name = "Zone B",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 461, DateTimeKind.Unspecified).AddTicks(4247), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("4f9f0f95-7408-44ad-a6f2-6f30f3e9a103"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 461, DateTimeKind.Unspecified).AddTicks(4267), new TimeSpan(0, 0, 0, 0, 0)),
                            EstimatedMaxMinutes = 110,
                            EstimatedMinMinutes = 70,
                            Fee = 40m,
                            IsActive = true,
                            MaxKm = 12m,
                            MinKm = 8m,
                            Name = "Zone C",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 461, DateTimeKind.Unspecified).AddTicks(4267), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("MessageStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("DeliveryZoneId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShopifyOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryZoneId");

                    b.HasIndex("ShopifyOrderId")
                        .IsUnique();

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubscriptionEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ShopifyProductId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShopifyProductId")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a201"),
                            Category = "Fresh Pastes",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 471, DateTimeKind.Unspecified).AddTicks(1319), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSubscriptionEnabled = true,
                            Name = "Premium Ginger Garlic Paste",
                            Slug = "premium-ginger-garlic-paste",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 471, DateTimeKind.Unspecified).AddTicks(1325), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a202"),
                            Category = "Fresh Pastes",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 471, DateTimeKind.Unspecified).AddTicks(3958), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSubscriptionEnabled = true,
                            Name = "Fresh Garlic Paste",
                            Slug = "fresh-garlic-paste",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 471, DateTimeKind.Unspecified).AddTicks(3959), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a203"),
                            Category = "Fresh Pastes",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 471, DateTimeKind.Unspecified).AddTicks(3964), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            IsSubscriptionEnabled = true,
                            Name = "Green Chilli Paste",
                            Slug = "green-chilli-paste",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 471, DateTimeKind.Unspecified).AddTicks(3965), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ShopifyVariantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopifyVariantId")
                        .IsUnique();

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("product_variants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f8f0f95-7408-44ad-a6f2-6f30f3e9a301"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 474, DateTimeKind.Unspecified).AddTicks(7512), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Label = "200 g",
                            Price = 99m,
                            ProductId = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a201"),
                            SalePrice = 94m,
                            Sku = "SF-GG-200",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 474, DateTimeKind.Unspecified).AddTicks(7521), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = "200 g"
                        },
                        new
                        {
                            Id = new Guid("8f8f0f95-7408-44ad-a6f2-6f30f3e9a302"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2615), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Label = "500 g",
                            Price = 219m,
                            ProductId = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a201"),
                            SalePrice = 209m,
                            Sku = "SF-GG-500",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2617), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = "500 g"
                        },
                        new
                        {
                            Id = new Guid("8f8f0f95-7408-44ad-a6f2-6f30f3e9a303"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2633), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Label = "200 g",
                            Price = 89m,
                            ProductId = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a202"),
                            SalePrice = 84m,
                            Sku = "SF-GA-200",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2634), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = "200 g"
                        },
                        new
                        {
                            Id = new Guid("8f8f0f95-7408-44ad-a6f2-6f30f3e9a304"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2640), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Label = "500 g",
                            Price = 199m,
                            ProductId = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a202"),
                            SalePrice = 189m,
                            Sku = "SF-GA-500",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2640), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = "500 g"
                        },
                        new
                        {
                            Id = new Guid("8f8f0f95-7408-44ad-a6f2-6f30f3e9a305"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2662), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Label = "150 g",
                            Price = 79m,
                            ProductId = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a203"),
                            SalePrice = 75m,
                            Sku = "SF-GC-150",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2662), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = "150 g"
                        },
                        new
                        {
                            Id = new Guid("8f8f0f95-7408-44ad-a6f2-6f30f3e9a306"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2672), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Label = "300 g",
                            Price = 149m,
                            ProductId = new Guid("7f8f0f95-7408-44ad-a6f2-6f30f3e9a203"),
                            SalePrice = 142m,
                            Sku = "SF-GC-300",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 7, 4, 0, 1, 475, DateTimeKind.Unspecified).AddTicks(2672), new TimeSpan(0, 0, 0, 0, 0)),
                            Weight = "300 g"
                        });
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeliveriesInCycle")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeliveryZoneId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextBillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PlanPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityPerDelivery")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryZoneId");

                    b.HasIndex("ProductId");

                    b.HasIndex("VariantId");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.SubscriptionDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("FulfilledOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FulfilledOrderId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("subscription_deliveries", (string)null);
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Address", b =>
                {
                    b.HasOne("SafaFoods.Core.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafaFoods.Core.Entities.DeliveryZone", "DeliveryZone")
                        .WithMany("Addresses")
                        .HasForeignKey("DeliveryZoneId");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryZone");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.NotificationLog", b =>
                {
                    b.HasOne("SafaFoods.Core.Entities.Customer", "Customer")
                        .WithMany("Notifications")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Order", b =>
                {
                    b.HasOne("SafaFoods.Core.Entities.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafaFoods.Core.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafaFoods.Core.Entities.DeliveryZone", "DeliveryZone")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryZoneId");

                    b.Navigation("Address");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryZone");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("SafaFoods.Core.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafaFoods.Core.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafaFoods.Core.Entities.ProductVariant", "Variant")
                        .WithMany("OrderItems")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.ProductVariant", b =>
                {
                    b.HasOne("SafaFoods.Core.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Subscription", b =>
                {
                    b.HasOne("SafaFoods.Core.Entities.Address", "Address")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafaFoods.Core.Entities.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafaFoods.Core.Entities.DeliveryZone", "DeliveryZone")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DeliveryZoneId");

                    b.HasOne("SafaFoods.Core.Entities.Product", "Product")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafaFoods.Core.Entities.ProductVariant", "Variant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryZone");

                    b.Navigation("Product");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.SubscriptionDelivery", b =>
                {
                    b.HasOne("SafaFoods.Core.Entities.Order", "FulfilledOrder")
                        .WithMany("SubscriptionDeliveries")
                        .HasForeignKey("FulfilledOrderId");

                    b.HasOne("SafaFoods.Core.Entities.Subscription", "Subscription")
                        .WithMany("Deliveries")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FulfilledOrder");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Address", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.DeliveryZone", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Orders");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SubscriptionDeliveries");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Subscriptions");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.ProductVariant", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SafaFoods.Core.Entities.Subscription", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
